# Generated by Django 5.0.4 on 2024-05-17 07:24

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_alter_contact_options_profile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "verbose_name": "3. Profile",
                "verbose_name_plural": "3. Profiles",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(upload_to=website.models.user_directory_path),
        ),
    ]
