# Generated by Django 5.0.4 on 2024-05-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventtype",
            options={
                "verbose_name": "1. Event Type",
                "verbose_name_plural": "1. Event Types",
            },
        ),
        migrations.AlterModelOptions(
            name="hms_event",
            options={
                "verbose_name": "2. Hms Event",
                "verbose_name_plural": "2. Hms Event",
            },
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="detail",
            field=models.TextField(null=True),
        ),
    ]
