# Generated by Django 5.0.4 on 2024-05-14 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_alter_eventtype_options_alter_hms_event_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_detail", models.TextField()),
                ("booking_date", models.DateTimeField(auto_now_add=True)),
                ("total_guest", models.IntegerField()),
                ("event_date", models.DateField()),
                (
                    "booking_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("booking_detail", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.eventtype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "2. Event Booking",
                "verbose_name_plural": "2. Event Booking",
            },
        ),
        migrations.CreateModel(
            name="payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txt_id", models.TextField()),
                ("total_amt", models.DecimalField(decimal_places=2, max_digits=10)),
                ("response_data", models.TextField()),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "eventbooking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.eventbooking",
                    ),
                ),
            ],
            options={
                "verbose_name": "3. Payment",
                "verbose_name_plural": "3. Payment",
            },
        ),
        migrations.DeleteModel(
            name="HMS_Event",
        ),
    ]
