# Generated by Django 5.0.4 on 2024-05-14 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_room_booking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "verbose_name": "3. Booking",
                "verbose_name_plural": "3. Bookings",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "2. Room", "verbose_name_plural": "2. Rooms"},
        ),
        migrations.AlterModelOptions(
            name="roomtype",
            options={
                "verbose_name": "1. Room Type",
                "verbose_name_plural": "1. Room Types",
            },
        ),
    ]
