# Generated by Django 5.0.4 on 2024-05-14 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0003_alter_booking_options_alter_room_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txt_id", models.TextField()),
                ("total_amt", models.DecimalField(decimal_places=2, max_digits=10)),
                ("response_data", models.TextField()),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rooms.booking"
                    ),
                ),
            ],
            options={
                "verbose_name": "4. Payment",
                "verbose_name_plural": "4. Payments",
            },
        ),
    ]
