# Generated by Django 5.0.4 on 2024-05-14 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0005_gallery_roomimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomimage",
            options={
                "verbose_name": "6. Room Images",
                "verbose_name_plural": "6. Room Images",
            },
        ),
    ]
